apiVersion: apps/v1
kind: Deployment
metadata:
  name: apikeystore
spec:
  template:
    spec:
      containers:
      - name: service
        env:
          - name: APIKEYSTORE_MODE
            value: "writer"

          - name: APIKEYSTORE_EXCHANGEURL
            valueFrom:
              configMapKeyRef:
                name: apikeystore
                key: APIKEYSTORE_EXCHANGEURL

          # current approach is to deploy a single tokenendpoint
          # in one namespace and manage its clients list manualy. The client
          # id secret here must match an entry configured for tokenendpoint
          # corresponding id/secret in it.
          - name: APIKEYSTORE_CLIENTID
            valueFrom:
              secretKeyRef:
                name: tokenendpoint-clientid-secret
                key: CLIENT_ID

          - name: APIKEYSTORE_CLIENTSECRET
            valueFrom:
              secretKeyRef:
                name: tokenendpoint-clientid-secret
                key: CLIENT_SECRET

