apiVersion: apps/v1
kind: Deployment
metadata:
  name: apikeystore
spec:
  template:
    spec:
      containers:
      - name: service
        env:
          - name: APIKEYSTORE_MODE
            value: "writer"
