commonLabels:
  app: apikeystore
resources:
  - deployment.yaml
  - service.yaml
patchesStrategicMerge:
  - deployment-serviceaccount.yaml
  - deployment-env.yaml
  - deployment-env-tokenendpoint.yaml
configMapGenerator:
  - name: apikeystore
    literals:
      - APIKEYSTORE_PROJECTID=iona-1
      - APIKEYSTORE_ADDRESS1=0.0.0.0:8401
      - APIKEYSTORE_ADDRESS2=0.0.0.0:8402
      - APIKEYSTORE_PREFIX=/
      - APIKEYSTORE_EXCHANGEURL=http://tokenendpoint:3000/token
