apiVersion: v1
kind: Service
metadata:
  name: auth-apikeystore
spec:
  clusterIP: None
  selector:
    app: auth-apikeystore
  ports:
    - name: http
      port: 80
      targetPort: 8401
    - name: http2
      port: 82
      targetPort: 8402

